import { Component } from '@angular/core';

@Component({
  selector: 'app-telecom',
  templateUrl: './telecom.component.html',
  styleUrls: ['./telecom.component.css'],
})
export class TelecomComponent {
  dataType: any = [
    {
      mainText: 'Web and Social Media',
      text: `For a telecommunications company, it is essential to know information about its clients or potential clients: interests, tastes, jobs, affective relationships, their behavior patterns on the network, etc. they can be collected from social media environments as fundamental information to design truly profitable advertising and promotional campaigns.`,
    },
    {
      mainText: 'M2M (Machine To Machine)',
      text: `Within the scope of the Internet of Things, the term M2M refers to the technologies that allow connection to other devices thanks to the use of sensors or event meters (speed, temperature, pressure, meteorological variables, chemical variables such as salinity, etc.), data that is transferred through networks (wired, wireless or hybrid) to other applications to be processed and thus have analyzed information.`,
    },
    {
      mainText: ' Data transactions',
      text: `This analysis includes data such as billing or call records, transactional data that can also be analyzed to establish patterns of customer behavior with which the company can predict possible cancellations, control fraud or carry out loyalty actions.`,
    },
    {
      mainText: 'Information generated by clients',
      text: `Users, in their relationship with the operator, generate a large amount of unstructured data (emails, phone calls, and documents) that, thanks to Big Data analytics, we can categorize based on their relevance for further analysis or discard.`,
    },
  ];

  cases = [
    'Targeted Marketing.',
    'Real-time Analytics.',
    'Fraud Detection.',
    'Increased Network Security.',
    'Preventing Customer Churn.',
    'Price Optimization.',
    'Predictive Analytics.',
    'Product Optimization.',
  ];
}
